### ISSUE TITLE
Multiple variable inputs?

### ISSUE THREAD

**Issue by RichardCimler** [auseckas/rsfuzzy#2]
It is not possible to pass multiple variables into calculate method.

In the rules, there can be multiple variables - var1, var2 etc...

Unfortunately you can pass only one value into calculate method:
pub fn calculate(&self, x: f32) -> f32 

For example:
f_engine.calculate(10.0); 

How to make a rule with for example: 
Temperature of water: 60 degrees
Flow: 10m/s
And rules where is a combination of these variables used?

f_engine.calculate(60.0, 10.0);  ???

Thank you :)

**Comment by auseckas** [comment]
Ok, I fixed a bunch of bugs and added proper multiple variable support.

You can see usage in the included example.

That being said, this library was one of my first projects in Rust and it is not being actively used. So there might be other issues - use it at your own risk.

**Comment by RichardCimler** [comment]
Thank you very much for fixing. 
Good work!
